### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Dzentsetsu** [Dzentsetsu/UDPchatApp#1]
- [ ] Display messages to all clients;
- [ ] Create sort of connection packet when first logged in; 
- [ ] Create dissconect packet when pressing exit buttom;
